### ISSUE TITLE
Font weights 

### ISSUE THREAD

**Issue by carolsinc** [carolsinc/fastness-fixer#1]
My Cormotant Garamond text is not the right weight, but all my attempts have failed or made it worse?

@hellachella
@HannahDelaney

**Comment by HannahDelaney** [comment]
Urg, such a small thing. I think it's defaulting to Garamond or something so looks the same, but you've got a typo.

You need "Cormorant Garamond" not "Cormotant Garamond".

That will fix it!

**Comment by HannahDelaney** [comment]
Gosh darn intentional typos...

**Comment by carolsinc** [comment]
I have been fighting with this for an hour lol. that fixed it!

**Comment by HannahDelaney** [comment]
Booo at least you've got it now!
